management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: '*'
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 0556559704Islam
        url: jdbc:mysql://localhost:3307/tes-api
        username: dark3
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
        show-sql: true
